// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXTgP_HZYmaiLvo19HEypIUpeCbp-6eBs',
    appId: '1:207704646040:web:e167845e6bba501c4acbed',
    messagingSenderId: '207704646040',
    projectId: 'spotify-clone-49f89',
    authDomain: 'spotify-clone-49f89.firebaseapp.com',
    storageBucket: 'spotify-clone-49f89.appspot.com',
    measurementId: 'G-HQDL1W7PG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj2RYmBQs4Af_HkTYaktAgjvsNC-AOrqU',
    appId: '1:207704646040:android:337cac91a1852e494acbed',
    messagingSenderId: '207704646040',
    projectId: 'spotify-clone-49f89',
    storageBucket: 'spotify-clone-49f89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd0DFqvjKwJhRWFwj7-n15xqbWdLPxPGI',
    appId: '1:207704646040:ios:2fbeff65c307e4c84acbed',
    messagingSenderId: '207704646040',
    projectId: 'spotify-clone-49f89',
    storageBucket: 'spotify-clone-49f89.appspot.com',
    iosBundleId: 'com.ahmadhabibshovo.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd0DFqvjKwJhRWFwj7-n15xqbWdLPxPGI',
    appId: '1:207704646040:ios:2fbeff65c307e4c84acbed',
    messagingSenderId: '207704646040',
    projectId: 'spotify-clone-49f89',
    storageBucket: 'spotify-clone-49f89.appspot.com',
    iosBundleId: 'com.ahmadhabibshovo.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXTgP_HZYmaiLvo19HEypIUpeCbp-6eBs',
    appId: '1:207704646040:web:3048e709b7b8e9a24acbed',
    messagingSenderId: '207704646040',
    projectId: 'spotify-clone-49f89',
    authDomain: 'spotify-clone-49f89.firebaseapp.com',
    storageBucket: 'spotify-clone-49f89.appspot.com',
    measurementId: 'G-LD7CECZTT9',
  );
}
